## Лабораторная работа №1 | Вариант 5

Выполнил:

### 1. Numpy

In [2]:
import numpy as np

1. Создайте единичную матрицу размером 3х3

In [3]:
m = np.eye(3)

2. Создайте кастомный dtype который описывает цвет состоящий из 4х unsigned bytes(RGBA пиксель)

In [4]:
rgba_data_type = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8),])

3. Как игнорировать все numpy warnings(не рекомендуем к использованию)?

In [5]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

4. Создайте случайный вектор размера 10 и отсортируйте его

In [6]:
v = np.random.rand(10)
sorted_v = np.sort(v)
print(sorted_v)

[0.28607474 0.30581866 0.41953607 0.43509613 0.67488779 0.68296414
 0.68458035 0.72559804 0.77698722 0.88085546]


5. Создайте read-only массив(неизменяемый)

In [13]:
arr = np.array([1, 1, 1,])
arr.flags.writeable = False
# arr[1] = 23456

6. Рассмотрим случайную матрицу размером 10х2, представляющую декартовы координаты, преобразуем их в полярные координаты

In [16]:
mtrx = np.random.randn(10, 2)
x, y = mtrx[:, 0], mtrx[ :, 1]
rad = np.sqrt(x ** 2 + y ** 2)
ang = np.arctan2(y, x)
polar = np.column_stack((rad, ang))
print(polar)

[[ 0.85422594 -2.46588837]
 [ 0.50110503  0.48562869]
 [ 0.81697182  2.92073884]
 [ 1.27080498 -2.76270664]
 [ 1.01538225 -0.34517238]
 [ 1.27717089 -2.27168907]
 [ 1.24237903  1.20108537]
 [ 0.14148232 -2.01747334]
 [ 1.60602792  1.85969894]
 [ 0.66075454  1.17523932]]


7. Создайте структурированный массив с координатами x и y, охватывающий область [0,1]x[0,1]

In [20]:
n = 10
x, y = np.linspace(0, 1, n), np.linspace(0, 1, n)
X, Y = np.meshgrid(x, y)
dtype = [('x', np.float64), ('y', np.float64)]
coords = np.zeros(X.shape, dtype=dtype)
coords['x'] = X
coords['y'] = Y

print(coords)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

8. Учитывая два массива X и Y, постройте матрицу Коши $C$ ($C_{ij} =\frac{1}{x_i - y_j}$)

In [22]:
x = np.random.normal(size=(5))
y = np.random.normal(size=(5))

c = np.array([[1 / (i - j) for j in y] for i in x])
print(c)

[[ -2.23752816  22.52744901   1.98872671   2.2339979   -5.02869014]
 [ -1.75596364 -12.79167667   2.62972309   3.07633745  -3.11114504]
 [ -0.33387347  -0.3993874   -0.48890417  -0.47605516  -0.36402238]
 [ -0.54185552  -0.73844426  -1.1163775   -1.05156821  -0.62599863]
 [ -0.26337443  -0.30252025  -0.35123215  -0.34455122  -0.28178436]]


9. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [25]:
arr = np.array([-19.99999, 0.34, 1.3], dtype=np.float32)
print(arr, arr.dtype)
arr = arr.view(np.int32)
print(arr, arr.dtype)

[-19.99999   0.34      1.3    ] float32
[-1046478853  1051595899  1067869798] int32


10. Как случайно заменить p элементов в 2D массиве?

In [29]:
arr = np.arange(20).reshape(4, 5)
p = 7

np.put(arr, np.random.choice(range(arr.size), p, replace=False), -1)

print(arr)

[[-1  1  2  3  4]
 [ 5 -1 -1 -1 -1]
 [10 11 12 -1 -1]
 [15 16 17 18 19]]


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом

Классический начальный набор данных - данные пассажиров титаника.

Файл: `data.csv`

```
PassangerId - уникальный номер пассажира
Survived - выжил человек или нет
Pclass - класс обслуживания
Name - имя человека, обращение к ней/нему
Sex - пол человека
Age - возраст на момент крушения
SibSp - количество братьев и сестер / супругов на борту "Титаника"
Parch - количество родителей / детей на борту "Титаника"
Ticket - номер билета
Fare - стоимость проезда для пассажиров
Cabin - каюта
Embarked - причал отбытия. C = Cherbourg Q = Queenstown S = Southampton
```

In [ ]:
import pandas as pd

In [ ]:
# Load dataset here

1. Узнайте сколько было на борту человек

2. Какой медианный и средний возраста пассажиров

3. Посчитайте процент выживаемости детей(до 16 лет) и взрослых

4. Верна ли гипотеза, что женщины и дети сажались в шлюпки первыми и выживали больше?

5. Зависит ли выживаемость от класса обслуживания?

6. Посчитайте средний возраст умерших женщин и мужчин

7. Различается ли процент выживаемости пассажиров с хотя бы одним родственником на борту и одиночек?

8. Различается ли средняя стоимость билета у умерших и выживших пассажиров?

9. Выведите максимальный и минимальный возраст выживших пассажиров во 2 классе обслуживания

10. Подтвердите или опровергните гипотезу: молодым мужчинам(от 18 лет) выжить легче, чем более взрослым

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Постройте гистограмму распределения возростов пассажиров

2. Постройте гистограммы распределения цен для пассажиров разных классов

3. Постройте зависимость цены от возраста пассажира

4. Постройте box plot отображающий распределение цен на билеты в разных классах

5. Визуализируйте распределение долей выживших среди мужчин, женщин и детей(до 16 лет)

6. Сравните плотности распределения возростов выживших и умерших пассажиров, сделайте выводы

7. Постройте круговую диаграмму отображающую выживаемость мужчин и женщин в разных классах обслуживания(визуализация должна быть интуитивно понятная без объяснений, женщины и мужчины соответствующих классов объеденены визуально в одну группу и 2 подгруппы)*

\* Задание на доп. балл